name: CD - Publish to NPM

on:
  push:
    tags:
      - 'v*' # 仅在推送以 'v' 开头的 Tag 时触发，例如 v1.4.0

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run Lint
      run: yarn run lint

    - name: Run Tests
      run: yarn run test:all

    - name: Build Project
      run: yarn run build

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}